using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;

namespace OpenRA.Mods.Syw.AssetInstaller
{
	// utility.cmd --install-assets [GAME_FOLDER] [--out FOLDER] [--only STAGE,...] [--write-yaml] [--list]
	// Converts the art, palettes, music and maps from an original Seven Years War folder into the mod. GAME_FOLDER
	// defaults to a SYWAR folder next to the repository; the output goes into mods/syw (its generated paths are
	// gitignored) unless --out is given.
	sealed class InstallAssetsCommand : IUtilityCommand
	{
		string IUtilityCommand.Name => "--install-assets";

		bool IUtilityCommand.ValidateArguments(string[] args) => true;

		[Desc("[GAME_FOLDER]", "[--out FOLDER] [--only STAGE,...] [--write-yaml] [--list]",
			"Convert the assets of an original Seven Years War installation into the mod.")]
		void IUtilityCommand.Run(Utility utility, string[] args)
		{
			var modFolder = utility.ModData.Manifest.Package.Name;
			var options = args.Skip(1).ToList();

			if (options.Contains("--list"))
			{
				foreach (var stage in Stages.All)
					Console.WriteLine($"{stage.Name,-22} {stage.Description}");

				return;
			}

			var output = TakeValue(options, "--out") ?? modFolder;
			var only = TakeValue(options, "--only")?.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
			var writeYaml = options.Remove("--write-yaml");
			var gamePath = options.FirstOrDefault(o => !o.StartsWith("--", StringComparison.Ordinal))
				?? Path.Combine(modFolder, "..", "..", "..", "SYWAR");

			var unknown = only?.Where(name => Stages.All.All(s => s.Name != name)).ToList();
			if (unknown?.Count > 0)
				throw new ArgumentException($"Unknown stage(s): {string.Join(", ", unknown)}. Use --list to see them.");

			var game = new GameFolder(gamePath);
			var context = new InstallContext(game, output, modFolder, writeYaml);
			Console.WriteLine($"Seven Years War folder: {game.Root}");
			Console.WriteLine($"Writing to: {context.Output}");

			var total = Stopwatch.StartNew();
			foreach (var stage in Stages.All.Where(s => only == null || only.Contains(s.Name)))
			{
				var before = context.Written.Count;
				var watch = Stopwatch.StartNew();
				stage.Run(context);
				Console.WriteLine($"  {stage.Name,-22} {context.Written.Count - before,4} files  {watch.ElapsedMilliseconds,6} ms");
			}

			WriteManifest(context, merge: only != null);
			foreach (var warning in context.Warnings)
				Console.WriteLine($"WARNING: {warning}");

			Console.WriteLine($"Done: {context.Written.Count} files in {total.Elapsed.TotalSeconds:0.0} s.");
		}

		static string TakeValue(List<string> options, string name)
		{
			var i = options.IndexOf(name);
			if (i < 0)
				return null;

			if (i + 1 >= options.Count)
				throw new ArgumentException($"{name} needs a value.");

			var value = options[i + 1];
			options.RemoveRange(i, 2);
			return value;
		}

		// install-manifest.txt: one "sha256  path" line per generated file, so an install can be checked later. A partial
		// run (--only) updates the entries it wrote and keeps the others.
		static void WriteManifest(InstallContext context, bool merge)
		{
			var path = context.OutputPath("install-manifest.txt");
			var entries = new SortedDictionary<string, string>(StringComparer.Ordinal);
			if (merge && File.Exists(path))
				foreach (var line in File.ReadAllLines(path).Where(l => !l.StartsWith('#') && l.Contains("  ", StringComparison.Ordinal)))
				{
					var parts = line.Split("  ", 2);
					entries[parts[1]] = parts[0];
				}

			foreach (var (file, hash) in context.Written)
				entries[file] = hash;

			var text = new StringBuilder();
			text.Append("# Generated by --install-assets from ").Append(context.Game.Root).Append('\n');
			foreach (var (file, hash) in entries)
				text.Append(hash).Append("  ").Append(file).Append('\n');

			File.WriteAllText(path, text.ToString());
		}
	}
}
