using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace OpenRA.Mods.Syw.AssetInstaller
{
	// Where the converted game content lives and how an install runs. The mod loads it from the player's support folder
	// (mod.yaml mounts ^SupportDir|Content/syw/v1/), so the game itself needs no write access to its install folder. Both
	// the in-game installer (SywContentLogic) and utility.cmd --install-assets go through Run.
	public static class SywContent
	{
		// Bump (here and in mod.yaml) when the converter's output changes in a way an old install can't be used with;
		// existing players are then asked to convert again.
		public const string Version = "v1";

		// Written last, so its presence means the install finished (mod.yaml lists it in RequiredContentFiles).
		public const string ManifestFile = "install-manifest.txt";

		// Our own test maps (bot-test, ffa-spectate); only developers need them.
		public const string DeveloperStage = "maps";

		public static string Folder => Path.Combine(Platform.SupportDir, "Content", "syw", Version);

		public static IEnumerable<Stage> PlayerStages => Stages.All.Where(s => s.Name != DeveloperStage);

		// Converts the game in gameRoot into output, one stage at a time. progress(stage, index, count) is called before
		// each stage. Returns the warnings (generated YAML that differs from the repository copy, etc).
		public static List<string> Run(string gameRoot, string output, string modFolder, IEnumerable<Stage> stages,
			bool writeYaml = false, bool mergeManifest = false, Action<Stage, int, int> progress = null)
		{
			var game = new GameFolder(gameRoot);
			var context = new InstallContext(game, output, modFolder, writeYaml);
			var list = stages.ToList();

			// Until the new manifest is written the install counts as unfinished, so an interrupted run asks again.
			var manifest = Path.Combine(context.Output, ManifestFile);
			if (!mergeManifest && File.Exists(manifest))
				File.Delete(manifest);

			for (var i = 0; i < list.Count; i++)
			{
				progress?.Invoke(list[i], i, list.Count);
				list[i].Run(context);
			}

			WriteManifest(context, mergeManifest);
			return context.Warnings;
		}

		// install-manifest.txt: one "sha256  path" line per generated file, so an install can be checked later. A partial
		// run (--only) updates the entries it wrote and keeps the others.
		static void WriteManifest(InstallContext context, bool merge)
		{
			var path = context.OutputPath(ManifestFile);
			var entries = new SortedDictionary<string, string>(StringComparer.Ordinal);
			if (merge && File.Exists(path))
				foreach (var line in File.ReadAllLines(path).Where(l => !l.StartsWith('#') && l.Contains("  ", StringComparison.Ordinal)))
				{
					var parts = line.Split("  ", 2);
					entries[parts[1]] = parts[0];
				}

			foreach (var (file, hash) in context.Written)
				entries[file] = hash;

			var text = new StringBuilder();
			text.Append("# Generated by the OpenSYW asset installer from ").Append(context.Game.Root).Append('\n');
			foreach (var (file, hash) in entries)
				text.Append(hash).Append("  ").Append(file).Append('\n');

			File.WriteAllText(path, text.ToString());
		}

		// Folders where a copy of the game commonly sits: SYWAR and similar names at the root of every fixed drive, in
		// Games and Program Files, in the user's Desktop, Downloads and Documents, and next to OpenSYW itself.
		public static IEnumerable<string> Candidates()
		{
			var names = new[] { "SYWAR", "SYW", "Seven Years War", "SevenYearsWar" };
			var bases = new List<string>();

			foreach (var drive in DriveInfo.GetDrives().Where(d => d.DriveType == DriveType.Fixed && d.IsReady))
			{
				bases.Add(drive.RootDirectory.FullName);
				bases.Add(Path.Combine(drive.RootDirectory.FullName, "Games"));
			}

			var special = new[]
			{
				Environment.SpecialFolder.ProgramFilesX86, Environment.SpecialFolder.ProgramFiles,
				Environment.SpecialFolder.DesktopDirectory, Environment.SpecialFolder.MyDocuments, Environment.SpecialFolder.UserProfile
			};

			foreach (var folder in special)
			{
				var path = Environment.GetFolderPath(folder);
				if (!string.IsNullOrEmpty(path))
					bases.Add(path);
			}

			var profile = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
			if (!string.IsNullOrEmpty(profile))
				bases.Add(Path.Combine(profile, "Downloads"));

			// Next to the game: an installed OpenSYW (EngineDir is its folder), or a development checkout (engine/ inside
			// the repository, with SYWAR beside the repository).
			var engine = Platform.EngineDir.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
			bases.Add(engine);
			var parent = Path.GetDirectoryName(engine);
			if (parent != null)
			{
				bases.Add(parent);
				var grandparent = Path.GetDirectoryName(parent);
				if (grandparent != null)
					bases.Add(grandparent);
			}

			return bases.Distinct(StringComparer.OrdinalIgnoreCase).SelectMany(b => names.Select(n => Path.Combine(b, n)));
		}

		public static string Detect() => Candidates().FirstOrDefault(GameFolder.LooksLike);
	}
}
